# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5665e0840ba628d4329087b7de62e36ada1d8db51489a0ee11ffb54037483cc95b895f5dbe549f1367538079e88b80171f6e256191e6042973ba7e677697567

test:
  secret_key_base: b11d04fd4d8b261cf22c5380188ac16ebb8df91b381c80a763d1bc3e4844e88b637212e57238ff92462f144deaecf89e89f095410ca8b37feb9f80aa962607b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
